export const PRIMARY_COLOR = '#4fafd1';

export const REACT_APP_DOC_MAIN_SERVICE_URL = process.env.REACT_APP_DOC_MAIN_SERVICE_URL;

export const REACT_APP_DOC_FILE_SERVICE_URL = process.env.REACT_APP_DOC_FILE_SERVICE_URL;
