name: DOC build, push to Docker Hub and deploy

on:
  push:
    branches: [ dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hcmusdoc/doc-front:latest
  
  Deploy:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
      - name: Deploy 
        shell: bash
        run: echo Deploying...
