name: doc-front CD

on:
  push:
    branches: [ dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build dev
        run: yarn build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dev image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hcmusdoc/doc-front:dev-latest
      
      - name: Build local
        run: yarn build:local

      - name: Build production
        run: yarn build:prod

      - name: Build local image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hcmusdoc/doc-front:local-latest
